language: node_js
node_js:
- 6
script:
- npm run cover
notifications:
  slack:
    secure: 0A1ALke1DfDoXXPsc6NLMgCOx7jx/XlS0jxMwCm6CGFuwUSg6aPGsXQ1Mr+bMlseoX7qwfgKa/vJD+QopJT0SRSX68nT6FNOcLXZHOZqSwC1lGZxnrEMvZY1ZXc81KvcxXF6QT9TiMuWYRxWpRejNfViCXmuKfHMWOefnMS7a36OG9/IttbKq3a39VQOQmYvHVQneHaANNsr3iPFuFJwdLTvHeMxskLTxL0kV4vY5as8sCTOecRfSeUZpRMRErLsjoAG0fL6yYOVTG6NmU49Fnz/zsqEAJbKOdEuC0SpGWfTuD3d98Jy2MtIofkTtUYTBEL//CSDfzD9F7rr5D2M5IyIUGjnwNFmhc1O6obTyWowUUmpORqsOu7BFLcCnB/I2ExMBwaGMpP18KHXA1pykgiTCnlK8Rp43lIUszn1oEPJN2fXYttJjIl1Q/JJhJXWvEUzenu+FL7CB5+JnsRfWrdSNNIzmXJFoo6EuiuzXrPnKLi7xru3WOTRIWUSfH1W3mtFtHRSnvE7TX9fTXcTnGO3GrIRvYjyRbmsR3HtShEaUhkeDCq/8b7HjKwNKFKXyh6oaow+XG0ao2KgepuMphzsVLJ1wqXEL6UgSra1e8XKkiLJDf3NUd/qDqP2W1ju2LJQKoFJveR/HlidRaj2quiU53Zlle5cUiN1EJtnbAg=
