export const hitboxEmotesJSON = [
    {
        "icon_id": "1",
        "icon_name": "smile",
        "icon_short": ":)",
        "icon_short_alt": ": )",
        "icon_path": "/static/img/chat/default/smile3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "17",
        "icon_name": "tongue",
        "icon_short": ":xp:",
        "icon_short_alt": ":XP:",
        "icon_path": "/static/img/chat/default/tongue4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "33",
        "icon_name": "straightface7",
        "icon_short": ":thinking:",
        "icon_short_alt": ":thinking:",
        "icon_path": "/static/img/chat/default/straight7.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "49",
        "icon_name": "angry",
        "icon_short": "&gt;:(",
        "icon_short_alt": ":angry:",
        "icon_path": "/static/img/chat/default/angry1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "10",
        "icon_name": "iloveit",
        "icon_short": "xD",
        "icon_short_alt": "xD",
        "icon_path": "/static/img/chat/default/love1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "26",
        "icon_name": "straightface4",
        "icon_short": ":/",
        "icon_short_alt": ":/",
        "icon_path": "/static/img/chat/default/straight4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "42",
        "icon_name": "angry5",
        "icon_short": "DX",
        "icon_short_alt": "DX",
        "icon_path": "/static/img/chat/default/angry5.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "3",
        "icon_name": "ilike",
        "icon_short": ":&gt;",
        "icon_short_alt": ":&gt;",
        "icon_path": "/static/img/chat/default/smile5.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "19",
        "icon_name": "icame",
        "icon_short": ":E",
        "icon_short_alt": "icame",
        "icon_path": "/static/img/chat/default/icame.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "35",
        "icon_name": "surprised2",
        "icon_short": ":O",
        "icon_short_alt": ":omg:",
        "icon_path": "/static/img/chat/default/surprised2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "51",
        "icon_name": "sad",
        "icon_short": ":c",
        "icon_short_alt": ":C",
        "icon_path": "/static/img/chat/default/sad2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "12",
        "icon_name": "iloveu",
        "icon_short": "&lt;33",
        "icon_short_alt": "iloveu",
        "icon_path": "/static/img/chat/default/love2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "28",
        "icon_name": "surprised",
        "icon_short": ":o",
        "icon_short_alt": "8o",
        "icon_path": "/static/img/chat/default/surprised1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "44",
        "icon_name": "sad3",
        "icon_short": "D,:",
        "icon_short_alt": ";O;",
        "icon_path": "/static/img/chat/default/sad3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "5",
        "icon_name": "smile",
        "icon_short": "^_^",
        "icon_short_alt": "^^",
        "icon_path": "/static/img/chat/default/smile4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "21",
        "icon_name": "dealwithit",
        "icon_short": "8-)",
        "icon_short_alt": "(cool)",
        "icon_path": "/static/img/chat/default/glasses.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "37",
        "icon_name": "worried2",
        "icon_short": ":S",
        "icon_short_alt": ":S",
        "icon_path": "/static/img/chat/default/worried2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "53",
        "icon_name": "dizzy",
        "icon_short": "@_@",
        "icon_short_alt": "@_@",
        "icon_path": "/static/img/chat/default/dizzy.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "14",
        "icon_name": "innocent",
        "icon_short": "O:)",
        "icon_short_alt": ":innocent:",
        "icon_path": "/static/img/chat/default/innocent.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "30",
        "icon_name": "Oo",
        "icon_short": "O_o",
        "icon_short_alt": "O.o",
        "icon_path": "/static/img/chat/default/oo2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "46",
        "icon_name": "rage",
        "icon_short": ":rage:",
        "icon_short_alt": ":rage:",
        "icon_path": "/static/img/chat/default/angry2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "7",
        "icon_name": "derpsmile",
        "icon_short": "o.o",
        "icon_short_alt": "O.O",
        "icon_path": "/static/img/chat/default/derp1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "23",
        "icon_name": "sleepy",
        "icon_short": "u.u",
        "icon_short_alt": "U.U",
        "icon_path": "/static/img/chat/default/sleepy.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "39",
        "icon_name": "confounded",
        "icon_short": "xs",
        "icon_short_alt": "xs",
        "icon_path": "/static/img/chat/default/confounded.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "55",
        "icon_name": "puke",
        "icon_short": ":@",
        "icon_short_alt": ":puke:",
        "icon_path": "/static/img/chat/default/puke.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "16",
        "icon_name": "tongue",
        "icon_short": ";p",
        "icon_short_alt": ";P",
        "icon_path": "/static/img/chat/default/tongue1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "32",
        "icon_name": "straightface5",
        "icon_short": "o_o",
        "icon_short_alt": "o_o",
        "icon_path": "/static/img/chat/default/straight5.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "48",
        "icon_name": "freaked",
        "icon_short": ":freaked:",
        "icon_short_alt": "frkd",
        "icon_path": "/static/img/chat/default/angry4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "9",
        "icon_name": "smileD",
        "icon_short": ":DD",
        "icon_short_alt": ":rofl:",
        "icon_path": "/static/img/chat/default/lol2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "25",
        "icon_name": "straightface2",
        "icon_short": ":\\",
        "icon_short_alt": ":\\",
        "icon_path": "/static/img/chat/default/straight2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "41",
        "icon_name": "angry6",
        "icon_short": "X(",
        "icon_short_alt": "X(",
        "icon_path": "/static/img/chat/default/angry6.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "2",
        "icon_name": "smile",
        "icon_short": ":))",
        "icon_short_alt": ":)))",
        "icon_path": "/static/img/chat/default/smile2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "18",
        "icon_name": "pft",
        "icon_short": "pft",
        "icon_short_alt": "pft",
        "icon_path": "/static/img/chat/default/pft.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "34",
        "icon_name": "sad1",
        "icon_short": ":(",
        "icon_short_alt": ":&lt;",
        "icon_path": "/static/img/chat/default/sad1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "50",
        "icon_name": "x",
        "icon_short": ":x",
        "icon_short_alt": ":X",
        "icon_path": "/static/img/chat/default/X.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "11",
        "icon_name": "sweat",
        "icon_short": "^^\"",
        "icon_short_alt": "^^'",
        "icon_path": "/static/img/chat/default/sweat1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "27",
        "icon_name": "straightface3",
        "icon_short": "&gt;:/",
        "icon_short_alt": "&gt;:/",
        "icon_path": "/static/img/chat/default/straight3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "43",
        "icon_name": "surprised3",
        "icon_short": "O_O\"",
        "icon_short_alt": "O_O'",
        "icon_path": "/static/img/chat/default/surprised3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "4",
        "icon_name": "wink",
        "icon_short": ";)",
        "icon_short_alt": ";-)",
        "icon_path": "/static/img/chat/default/wink1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "20",
        "icon_name": "toothderp",
        "icon_short": ":|=",
        "icon_short_alt": "toothderp",
        "icon_path": "/static/img/chat/default/derp2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "36",
        "icon_name": "worried",
        "icon_short": ":s",
        "icon_short_alt": ":s",
        "icon_path": "/static/img/chat/default/worried.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "52",
        "icon_name": "sad4",
        "icon_short": "T_T",
        "icon_short_alt": "T_T",
        "icon_path": "/static/img/chat/default/sad4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "13",
        "icon_name": "kissing_heart",
        "icon_short": ":*",
        "icon_short_alt": ":-*",
        "icon_path": "/static/img/chat/default/love3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "29",
        "icon_name": "oO",
        "icon_short": "o_O",
        "icon_short_alt": "o.O",
        "icon_path": "/static/img/chat/default/oo1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "45",
        "icon_name": "scream",
        "icon_short": "8O",
        "icon_short_alt": ":scream:",
        "icon_path": "/static/img/chat/default/scream2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "6",
        "icon_name": "blush",
        "icon_short": "://)",
        "icon_short_alt": ":blush:",
        "icon_path": "/static/img/chat/default/blush.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "22",
        "icon_name": "sleeping",
        "icon_short": "u_u",
        "icon_short_alt": "U_U",
        "icon_path": "/static/img/chat/default/sleeping.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "38",
        "icon_name": "surprised4",
        "icon_short": ":OO",
        "icon_short_alt": ":oo",
        "icon_path": "/static/img/chat/default/surprised4.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "54",
        "icon_name": "tongue",
        "icon_short": "8p",
        "icon_short_alt": "8P",
        "icon_path": "/static/img/chat/default/tongue3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "15",
        "icon_name": "tongue",
        "icon_short": ":p",
        "icon_short_alt": ":P",
        "icon_path": "/static/img/chat/default/tongue2.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "31",
        "icon_name": "straightface6",
        "icon_short": "O_O",
        "icon_short_alt": "O_O",
        "icon_path": "/static/img/chat/default/straight6.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "47",
        "icon_name": "ragefu",
        "icon_short": ":-||",
        "icon_short_alt": "ragefu",
        "icon_path": "/static/img/chat/default/angry3.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "8",
        "icon_name": "lol",
        "icon_short": ":D",
        "icon_short_alt": ":lol:",
        "icon_path": "/static/img/chat/default/lol1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "24",
        "icon_name": "straightface",
        "icon_short": ":|",
        "icon_short_alt": "straightface",
        "icon_path": "/static/img/chat/default/straight1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "40",
        "icon_name": "troubled",
        "icon_short": "&gt;_&lt;",
        "icon_short_alt": "&gt;.&lt;",
        "icon_path": "/static/img/chat/default/x1.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "56",
        "icon_name": "dead",
        "icon_short": "X_X",
        "icon_short_alt": "X_X",
        "icon_path": "/static/img/chat/default/dead.png",
        "category_id": "1",
        "category_name": "defaultfaces",
        "category_logo": "/static/img/chat/default/smile4.png",
        "channel": null
    },
    {
        "icon_id": "68",
        "icon_name": "vulcan",
        "icon_short": ":vulcan:",
        "icon_short_alt": ":vulcan:",
        "icon_path": "/static/img/chat/default/vulcan.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "84",
        "icon_name": "boom",
        "icon_short": ":BOOM:",
        "icon_short_alt": ":boom:",
        "icon_path": "/static/img/chat/default/boom.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "61",
        "icon_name": "thumbsdown",
        "icon_short": ":N:",
        "icon_short_alt": ":n:",
        "icon_path": "/static/img/chat/default/thumbsdown.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "77",
        "icon_name": "hankey",
        "icon_short": ":hankey:",
        "icon_short_alt": ":hankey:",
        "icon_path": "/static/img/chat/default/hankey.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "70",
        "icon_name": "fist_bump",
        "icon_short": ":fist_bump:",
        "icon_short_alt": ":fist_bump:",
        "icon_path": "/static/img/chat/default/fist_bump.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "63",
        "icon_name": "hand_ok",
        "icon_short": ":ok:",
        "icon_short_alt": ":ok:",
        "icon_path": "/static/img/chat/default/hand_ok.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "79",
        "icon_name": "smiling_imp",
        "icon_short": ":imp:",
        "icon_short_alt": ":imp:",
        "icon_path": "/static/img/chat/default/smilingimp.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "72",
        "icon_name": "stone",
        "icon_short": ":stone:",
        "icon_short_alt": ":stone:",
        "icon_path": "/static/img/chat/default/stone.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "65",
        "icon_name": "clap",
        "icon_short": ":clap:",
        "icon_short_alt": ":clap:",
        "icon_path": "/static/img/chat/default/clap.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "81",
        "icon_name": "heart",
        "icon_short": "&lt;3",
        "icon_short_alt": ":heart:",
        "icon_path": "/static/img/chat/default/heart.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "74",
        "icon_name": "pray",
        "icon_short": ":pray:",
        "icon_short_alt": ":pray:",
        "icon_path": "/static/img/chat/default/pray.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "67",
        "icon_name": "highfive",
        "icon_short": "^5",
        "icon_short_alt": ":highfive:",
        "icon_path": "/static/img/chat/default/highfive.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "83",
        "icon_name": "goodgame",
        "icon_short": ":GG:",
        "icon_short_alt": ":gg:",
        "icon_path": "/static/img/chat/default/gg.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "76",
        "icon_name": "flex",
        "icon_short": ":flex:",
        "icon_short_alt": ":flex:",
        "icon_path": "/static/img/chat/default/flex.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "60",
        "icon_name": "thumbsup",
        "icon_short": ":Y:",
        "icon_short_alt": ":y:",
        "icon_path": "/static/img/chat/default/thumbsup.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "69",
        "icon_name": "wave",
        "icon_short": ":wave:",
        "icon_short_alt": ":wave:",
        "icon_path": "/static/img/chat/default/wave.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "85",
        "icon_name": "tumbleweed",
        "icon_short": "...@",
        "icon_short_alt": "..@",
        "icon_path": "/static/img/chat/default/tumbleweed.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "62",
        "icon_name": "fingers_crossed",
        "icon_short": ":fingers_crossed:",
        "icon_short_alt": ":fingers_crossed:",
        "icon_path": "/static/img/chat/default/crossed_fingers.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "78",
        "icon_name": "skull",
        "icon_short": ":skull:",
        "icon_short_alt": ":skull:",
        "icon_path": "/static/img/chat/default/skull.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "71",
        "icon_name": "scissors",
        "icon_short": ":scissors:",
        "icon_short_alt": ":scissors:",
        "icon_path": "/static/img/chat/default/scissors.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "64",
        "icon_name": "hand_metal",
        "icon_short": ":metal:",
        "icon_short_alt": ":metal:",
        "icon_path": "/static/img/chat/default/metal.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "80",
        "icon_name": "ghost",
        "icon_short": ":ghost:",
        "icon_short_alt": ":ghost:",
        "icon_path": "/static/img/chat/default/ghost.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "73",
        "icon_name": "paper",
        "icon_short": ":paper:",
        "icon_short_alt": ":paper:",
        "icon_path": "/static/img/chat/default/paper.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "66",
        "icon_name": "victory",
        "icon_short": ":V:",
        "icon_short_alt": ":victory:",
        "icon_path": "/static/img/chat/default/v.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "82",
        "icon_name": "brokenheart",
        "icon_short": "&lt;/3",
        "icon_short_alt": ":u:",
        "icon_path": "/static/img/chat/default/heart2.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "75",
        "icon_name": "pistol",
        "icon_short": ":pistol:",
        "icon_short_alt": ":pistol:",
        "icon_path": "/static/img/chat/default/pistol.png",
        "category_id": "2",
        "category_name": "things",
        "category_logo": "/static/img/chat/default/metal.png",
        "channel": null
    },
    {
        "icon_id": "835",
        "icon_name": "m-genius-rage-face",
        "icon_short": "geniusrageface",
        "icon_short_alt": "geniusrageface",
        "icon_path": "/static/img/chat/memes/genius-rage-face.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "851",
        "icon_name": "m-y-u-no",
        "icon_short": "yuno",
        "icon_short_alt": "yuno",
        "icon_path": "/static/img/chat/memes/y-u-no.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "828",
        "icon_name": "m-epic-win",
        "icon_short": "epicwin",
        "icon_short_alt": "epicwin",
        "icon_path": "/static/img/chat/memes/epic-win.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "844",
        "icon_name": "m-pffftttchh",
        "icon_short": "pffftttchh",
        "icon_short_alt": "pffftttchh",
        "icon_path": "/static/img/chat/memes/pffftttchh.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "821",
        "icon_name": "m-cereal-guy",
        "icon_short": "cerealguy",
        "icon_short_alt": "cerealguy",
        "icon_path": "/static/img/chat/memes/cereal-guy.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "837",
        "icon_name": "m-i-lied",
        "icon_short": "ilied",
        "icon_short_alt": "ilied",
        "icon_path": "/static/img/chat/memes/i-lied.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "830",
        "icon_name": "m-forever-alone-happy",
        "icon_short": "foreveralonehappy",
        "icon_short_alt": "foreveralonehappy",
        "icon_path": "/static/img/chat/memes/forever-alone-happy.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "846",
        "icon_name": "m-so-hardcore",
        "icon_short": "sohardcore",
        "icon_short_alt": "sohardcore",
        "icon_path": "/static/img/chat/memes/so-hardcore.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "823",
        "icon_name": "m-concentrated-red-tongue",
        "icon_short": "concentratedredtongue",
        "icon_short_alt": "concentratedredtongue",
        "icon_path": "/static/img/chat/memes/concentrated-red-tongue.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "839",
        "icon_name": "m-look-of-disapproval",
        "icon_short": "lookofdisapproval",
        "icon_short_alt": "lookofdisapproval",
        "icon_path": "/static/img/chat/memes/look-of-disapproval.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "832",
        "icon_name": "m-fu",
        "icon_short": "fuuuu",
        "icon_short_alt": "fuuuu",
        "icon_path": "/static/img/chat/memes/fu.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "848",
        "icon_name": "m-troll-face",
        "icon_short": "trollface",
        "icon_short_alt": "trollface",
        "icon_path": "/static/img/chat/memes/troll-face.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "825",
        "icon_name": "m-derp",
        "icon_short": "mderp",
        "icon_short_alt": "mderp",
        "icon_path": "/static/img/chat/memes/derp.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "841",
        "icon_name": "m-me-gusta",
        "icon_short": "megusta",
        "icon_short_alt": "megusta",
        "icon_path": "/static/img/chat/memes/me-gusta.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "834",
        "icon_name": "m-fuck-yea",
        "icon_short": "fuckyea",
        "icon_short_alt": "fuckyea",
        "icon_path": "/static/img/chat/memes/fuck-yea.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "850",
        "icon_name": "m-ultrafacepalm",
        "icon_short": "ultrafacepalm",
        "icon_short_alt": "ultrafacepalm",
        "icon_path": "/static/img/chat/memes/ultrafacepalm.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "827",
        "icon_name": "m-disgusted-mother-of-god",
        "icon_short": "disgustedmotherofgod",
        "icon_short_alt": "disgustedmotherofgod",
        "icon_path": "/static/img/chat/memes/disgusted-mother-of-god.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "843",
        "icon_name": "m-okay",
        "icon_short": "mokay",
        "icon_short_alt": "mokay",
        "icon_path": "/static/img/chat/memes/okay.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "852",
        "icon_name": "m-you-what-have-you-done",
        "icon_short": "youwhathaveyoudone",
        "icon_short_alt": "youwhathaveyoudone",
        "icon_path": "/static/img/chat/memes/you-what-have-you-done.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "836",
        "icon_name": "m-i-dont-care",
        "icon_short": "idontcare",
        "icon_short_alt": "idontcare",
        "icon_path": "/static/img/chat/memes/i-dont-care.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "829",
        "icon_name": "m-fap",
        "icon_short": "fapfapfap",
        "icon_short_alt": "fapfapfap",
        "icon_path": "/static/img/chat/memes/fap.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "845",
        "icon_name": "m-raisins-face",
        "icon_short": "raisinsface",
        "icon_short_alt": "raisinsface",
        "icon_path": "/static/img/chat/memes/raisins-face.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "822",
        "icon_name": "m-challenge-accepted",
        "icon_short": "challengeaccepted",
        "icon_short_alt": "challengeaccepted",
        "icon_path": "/static/img/chat/memes/challenge-accepted.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "838",
        "icon_name": "m-lol",
        "icon_short": "lololol",
        "icon_short_alt": "lololol",
        "icon_path": "/static/img/chat/memes/lol.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "831",
        "icon_name": "m-forever-alone",
        "icon_short": "foreveralone",
        "icon_short_alt": "foreveralone",
        "icon_path": "/static/img/chat/memes/forever-alone.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "847",
        "icon_name": "m-sweet-jesus",
        "icon_short": "sweetjesus",
        "icon_short_alt": "sweetjesus",
        "icon_path": "/static/img/chat/memes/sweet-jesus.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "824",
        "icon_name": "m-crybaby",
        "icon_short": "mcrybaby",
        "icon_short_alt": "mcrybaby",
        "icon_path": "/static/img/chat/memes/crybaby.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "840",
        "icon_name": "m-mamaijustkilledaman",
        "icon_short": "mamah",
        "icon_short_alt": "mamaijustkilledaman",
        "icon_path": "/static/img/chat/memes/mamaijustkilledaman.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "833",
        "icon_name": "m-fuck-all-the-logic",
        "icon_short": "fuckallthelogic",
        "icon_short_alt": "fuckallthelogic",
        "icon_path": "/static/img/chat/memes/fuck-all-the-logic.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "849",
        "icon_name": "m-u-jelly",
        "icon_short": "ujelly",
        "icon_short_alt": "ujelly",
        "icon_path": "/static/img/chat/memes/u-jelly.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "826",
        "icon_name": "m-derpina",
        "icon_short": "mderpina",
        "icon_short_alt": "mderpina",
        "icon_path": "/static/img/chat/memes/derpina.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    },
    {
        "icon_id": "842",
        "icon_name": "m-no",
        "icon_short": "mNO",
        "icon_short_alt": "nNO",
        "icon_path": "/static/img/chat/memes/no.png",
        "category_id": "3",
        "category_name": "memes",
        "category_logo": "/static/img/chat/memes/u-jelly.png",
        "channel": null
    }
];
